"""remove_projects_table

Revision ID: 3d8daeab60ea
Revises: 30067db38089
Create Date: 2026-06-19 20:17:23.177578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d8daeab60ea'
down_revision: Union[str, Sequence[str], None] = '30067db38089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_id', table_name='projects')
    op.drop_index('ix_projects_slug', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('detailed_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('estimated_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('innovation_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('suggested_stack', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('target_audience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('market_potential', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_benefits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('implementation_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('theme', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('design_style', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='projects_pkey')
    )
    op.create_index('ix_projects_slug', 'projects', ['slug'], unique=True)
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    # ### end Alembic commands ###
